[package]
name = "MyPortfolioWebsite2"
version = "0.1.0"
edition = "2021"

[dependencies]
stylist = { version = "0.13.0", features = ["yew", "parser"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
